name: Backend CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      FIRESTORE_EMULATOR_HOST: "127.0.0.1:8080"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup Java (for Firebase emulators)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install deps (root)
        run: npm ci

      - name: Install deps (functions)
        working-directory: functions
        run: npm ci

      - name: Run unit tests
        run: npm test

      - name: Run Firestore rules tests
        run: |
          cd $GITHUB_WORKSPACE
          npx firebase emulators:exec --only firestore "npm run test:rules:run"