name: Deploy Chofer Functions

on:
  push:
    branches:
      - main

jobs:
  deploy-chofer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Write Firebase service account key
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > "${RUNNER_TEMP}/firebase-key.json"
          echo "GOOGLE_APPLICATION_CREDENTIALS=${RUNNER_TEMP}/firebase-key.json" >> $GITHUB_ENV
          echo "FIREBASE_PROJECT=taxipro-chofer" >> $GITHUB_ENV

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install deps (functions) if needed
        run: |
          if [ -f ./functions/package-lock.json ]; then
            npm --prefix ./functions ci
          else
            npm --prefix ./functions install
          fi

      - name: Build (functions) if script exists
        run: |
          if node -e "const p=require('./functions/package.json'); process.exit(!(p.scripts && p.scripts.build));"; then
            npm --prefix ./functions run build
          else
            echo "No build script, skipping build"
          fi



      - name: Run Tests
        run: npm test
        working-directory: ./functions

      - name: Deploy Functions (LIVE)
        run: firebase deploy --only functions --project taxipro-chofer --non-interactive
