name: e2e-emulators

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Install functions deps
        run: npm ci --prefix functions

      - name: Firebase Tools Version
        run: npx firebase-tools --version

      - name: E2E requestRide
        run: npx firebase emulators:exec --project taxipro-chofer --only auth,firestore,functions -- node ./tools/e2e_requestRide.js

      - name: E2E assign
        run: npx firebase emulators:exec --project taxipro-chofer --only auth,firestore,functions -- node ./tools/e2e_assign.js

      - name: E2E status
        run: npx firebase emulators:exec --project taxipro-chofer --only auth,firestore,functions -- node ./tools/e2e_status.js

      - name: E2E payment
        run: npx firebase emulators:exec --project taxipro-chofer --only auth,firestore,functions -- node ./tools/e2e_payment.js
